Updated the autogen header feature
fplab/rustviz pull request #31
Opened 2021-07-21 12:40 UTC by jisonZ

The tool is now capable of automatically generate ResourceAccessPoint.

2021-07-27 01:34 UTC, cyrus- requested changes

2021-07-27 01:34 UTC, cyrus- commented on INSTRUCTIONS.md
> +For this extra credit assignment, you will generate visualizations of Rust programs by annotating code according to the specifications found in the README file.
Discussion about the extra credit assignment shouldn't be in the main repo.

2021-07-27 01:34 UTC, cyrus- commented on README.md
> +Notice that the definition header now could be automatically generated by running the [view_examples.sh](rustviz_mdbook/view_examples.sh) once. If any incorrect information appeared at the generated
Remove "Notice that", change "could" -> "can" (present tense, not past, in things like this)

2021-07-27 01:34 UTC, cyrus- commented on RustvizParse/Cargo.toml
> +authors = ["Haochen Zhang <haochenz@Haochens-MacBook-Pro.local>"]
add at least myself to the authors list (and any of the other students that have contributed to this code), and fix the email address, also the "edition" shouldn't be "2018"

2021-07-30 04:27 UTC, cyrus- approved these changes
Didn't review the code in detail, but the README delta looks good now. Ready to merge when you are.

2021-07-30 05:39 UTC, jesssleepy approved these changes
Except that the recursive check of function calls in macros misses some new functions, the other functions I've tested work well.

2021-07-30 12:19 UTC, merged